"""Regenerates layoutIndex.ts (lightweight per-layout metadata: ratio/count,
no zone geometry) from the actual .json layout files - run this any time
layout files are added, renamed or removed."""

import json
import os

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LAYOUTS_DIR = os.path.join(_REPO_ROOT, "frontend/src/modules/photo-assembly/layouts")
OUT_FILE = os.path.join(_REPO_ROOT, "frontend/src/modules/photo-assembly/layoutIndex.ts")

RATIO_LABELS = ["16x9", "1x0.54", "1x1.44", "1x1", "2x3", "3x2", "3x4", "4x3", "4x5", "9x16"]
# longest-first so e.g. "1x0.54" isn't mistaken for a prefix of another label
RATIO_LABELS_SORTED = sorted(RATIO_LABELS, key=len, reverse=True)

entries = []
skipped = []
for fname in sorted(os.listdir(LAYOUTS_DIR)):
    if not fname.endswith(".json"):
        continue
    stem = fname[:-len(".json")]
    matched_ratio = None
    for r in RATIO_LABELS_SORTED:
        if stem.endswith("-" + r):
            matched_ratio = r
            break
    if not matched_ratio:
        skipped.append(fname)
        continue
    with open(os.path.join(LAYOUTS_DIR, fname)) as f:
        data = json.load(f)
    entries.append({
        "id": data.get("id", stem),
        "path": f"./layouts/{fname}",
        "ratio": matched_ratio,
        "aspectRatio": data.get("aspectRatio", 1),
        "count": len(data.get("zones", [])),
    })

print(f"Indexed {len(entries)} layouts, skipped {len(skipped)}: {skipped[:10]}")

with open(OUT_FILE, "w") as f:
    f.write("// Auto-generated by scripts/build_layout_index.py - do not hand-edit.\n")
    f.write("// Lightweight metadata (ratio/count) for every layout file, WITHOUT its\n")
    f.write("// zone geometry - lets the layout picker filter by orientation/ratio/photo\n")
    f.write("// count before dynamically importing only the matching file(s), instead of\n")
    f.write("// having to load all 4000+ layouts just to know which ones qualify.\n")
    f.write("export interface LayoutIndexEntry {\n")
    f.write("  id: string\n")
    f.write("  path: string\n")
    f.write("  ratio: string\n")
    f.write("  aspectRatio: number\n")
    f.write("  count: number\n")
    f.write("}\n\n")
    f.write("export const LAYOUT_INDEX: LayoutIndexEntry[] = ")
    json.dump(entries, f, separators=(",", ":"))
    f.write("\n")

print(f"Wrote {OUT_FILE}")
