#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Génère un fichier JavaScript contenant les images de saison en base64.
Ce fichier sera utilisé dans pdf.js pour afficher les fruits/légumes autour
des intercalaires de mois.
"""

import os
import base64
import json
from pathlib import Path

IMAGES_DIR = Path(__file__).parent / "images"
OUTPUT_FILE = Path(__file__).parent.parent / "backend" / "src" / "seasonal_images.js"


def get_mime_type(filename: str) -> str:
    ext = filename.lower().split(".")[-1]
    return {
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "webp": "image/webp",
    }.get(ext, "image/png")


def get_display_name(filename: str) -> str:
    """Extrait un nom lisible depuis le nom de fichier."""
    # filename format: nom_slug_hash.ext
    name = filename.rsplit("_", 1)[0]  # Enlève le hash
    name = name.replace("_", " ").title()
    return name


MAX_IMAGES_PER_MONTH = 12  # Limite pour garder le fichier léger


def main():
    seasonal_images = {}

    for month_num in range(1, 13):
        month_dir = IMAGES_DIR / f"{month_num:02d}"
        if not month_dir.exists():
            print(f"  Dossier manquant: {month_dir}")
            continue

        month_images = []
        image_files = sorted(month_dir.iterdir())

        for img_file in image_files[:MAX_IMAGES_PER_MONTH]:
            if img_file.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"}:
                continue

            try:
                with open(img_file, "rb") as f:
                    data = f.read()

                b64 = base64.b64encode(data).decode("utf-8")
                mime = get_mime_type(img_file.name)
                name = get_display_name(img_file.stem)

                month_images.append({
                    "name": name,
                    "data": f"data:{mime};base64,{b64}"
                })
                print(f"  + {month_num:02d}/{img_file.name} ({len(data)} bytes)")

            except Exception as e:
                print(f"  ! Erreur {img_file.name}: {e}")

        seasonal_images[month_num] = month_images
        print(f"Mois {month_num:02d}: {len(month_images)} images")

    # Générer le fichier JS
    js_content = f"""// Auto-generated by generate_seasonal_images_base64.py
// DO NOT EDIT MANUALLY

const SEASONAL_IMAGES = {json.dumps(seasonal_images, ensure_ascii=False)};

// Export for use in pdf.js
if (typeof module !== 'undefined') {{
  module.exports = {{ SEASONAL_IMAGES }};
}}
"""

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)

    total = sum(len(imgs) for imgs in seasonal_images.values())
    print(f"\n✓ Généré: {OUTPUT_FILE}")
    print(f"  Total: {total} images pour 12 mois")


if __name__ == "__main__":
    main()
